field: 85898001-9c9c-4d46-abf9-a928e44f0d48 # Body Content
fieldLayouts:
  e019c4eb-626d-410a-8d6a-0e6c3ac780c8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5aea2dce-a401-4e9f-8563-7a5a312f644b # Content Section
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 474885d3-68f2-4832-9907-fa3ebe9451ec
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3448704d-6165-474e-8426-15a12a7b3c37
        userCondition: null
fields:
  5aea2dce-a401-4e9f-8563-7a5a312f644b: # Content Section
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: contentSection
    instructions: 'Select the desired type in the drop-down field at the top right.'
    name: 'Content Section'
    searchable: false
    settings:
      allowSelfRelations: false
      localizeRelations: false
      maxRelations: null
      minRelations: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Entry
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\entries\EntryCondition
      selectionLabel: 'Add a content section'
      showSiteMenu: false
      source: null
      sources:
        - 'section:a1bd5e0e-3bf9-428d-a4f5-bebd6b3c1692' # Content Section
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: contentSection
name: 'Content Section'
sortOrder: 9
