fieldLayouts:
  e767c53c-c8f3-4d60-aa50-62d62cd925ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 75a11a3c-231c-416d-a777-faafe649ff27
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\LevelConditionRule
                  maxValue: ''
                  operator: '='
                  uid: 158643ce-7b35-45f6-8535-e81b1ca2d9be
                  value: '2'
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: e2e51276-3783-49cb-9ed0-22ae364fd49a # Menu Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 72250e68-b826-47ad-95ed-9b74c858bea6
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 1f5834fd-ed0d-466a-b4dd-2891fd144893 # Show Structure Navigation
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f60a45b3-9967-42ed-b54a-fa93f3028fd0
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 400d2e7a-d260-459d-b16d-bc388f093106 # Tagline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd2fb999-d293-46b6-bcac-088055a9e0da
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a3286bb-91f7-47ba-9862-9d102a8cf5d0 # Show Hero Area
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2d69ae0-cf28-403e-87c9-2db4f9144629
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 9a3286bb-91f7-47ba-9862-9d102a8cf5d0 # Show Hero Area
                  uid: da2ae03e-2fa2-4c91-9bb9-cf0c186db96e
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1cb67e0-22a1-44e1-824a-9d5957072f95
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 9a3286bb-91f7-47ba-9862-9d102a8cf5d0 # Show Hero Area
                  uid: c7a3dd79-0250-418e-806b-d42f663f5698
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 655243f7-46a2-42c0-8de4-188017c31d53 # Hero Area Template
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8184f611-e0f4-4d14-8db1-08e217705134
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 2f9975bd-3ee0-4f17-96cc-e91a163964dc # Content Sections
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 383b0df4-53e8-4d99-86b3-f581edf0ce64
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 52dab37d-cfe0-4bd7-85ef-3cf6d66f8dd6
        userCondition: null
handle: contentSections
hasTitleField: true
name: 'Content Sections'
section: 84b98802-2548-4aed-b67e-fc97f6ed9e30 # Page
sortOrder: 13
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
