fieldLayouts:
  aee8b4ab-cda8-4a5f-a7a3-f3efcc1d74be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8350d2ae-3d7d-4d96-aeae-eab90a7f0d5b # Hero Teaser
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c245459d-5dab-4726-b2d9-d2a0b748dd8b
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Hero Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 96ef4529-1abd-4c5c-9487-44ff965f7611
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7df417e8-1eea-46d8-85a7-2a20370a881e # Hero Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6e54432f-c93b-45d7-a68e-cbcdb522ed4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cce7e62c-f710-40fd-b9e9-71ba6f58265f # Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c7f6faa-9f00-4d1d-830a-4533f55aff35
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: CTA
            type: craft\fieldlayoutelements\Heading
            uid: e46dd8dc-23df-436d-8254-fb77a656369a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 08f7545c-870e-4727-a418-660af19052ea # CTA Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8cd30983-5d8a-4c19-8d71-61e410aa5ff3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: Layout
            type: craft\fieldlayoutelements\Heading
            uid: b5509a70-3403-4dd3-a8db-77f6adecd776
            userCondition: null
          -
            elementCondition: null
            fieldUid: 655243f7-46a2-42c0-8de4-188017c31d53 # Hero Area Template
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f384736a-6635-4904-a48d-5d10367a48cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f404ecd-d5b1-42b3-a674-5d6a0745c5f5
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 27127353-b8d1-4c07-a2af-7a273ad8f1f6 # Hero Area
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
