columnSuffix: kuvshphg
contentColumnType: datetime
fieldGroup: cf487444-d6c2-4c99-9432-e229efa674a2 # Person
handle: birthday
instructions: null
name: Birthday
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
