columnSuffix: null
contentColumnType: string
fieldGroup: 320fb86e-2364-403c-b8e9-152bac87d58f # Environment variables
handle: blitzCachingEnabled
instructions: '0 / 1'
name: 'Blitz Caching Enabled'
searchable: false
settings:
  validationRule: boolean
  variableName: BLITZ_CACHING_ENABLED
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
