columnSuffix: oxfnosrj
contentColumnType: string
fieldGroup: d50026f3-a236-4ae2-b00a-af55076acd17 # Site
handle: cardContentTemplateRoot
instructions: 'Plugins only.'
name: 'Card Content Template Root'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: string
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
