columnSuffix: wcgkvvuu
contentColumnType: string(240)
fieldGroup: d50026f3-a236-4ae2-b00a-af55076acd17 # Site
handle: copyright
instructions: 'For images: This is the information that must be legally displayed, usually the name of the photographer, for microstock images the name of the service if applicable. Leave blank if nothing is to be displayed on the website.'
name: Copyright
searchable: false
settings:
  byteLimit: null
  charLimit: 60
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
