columnSuffix: null
contentColumnType: string
fieldGroup: 320fb86e-2364-403c-b8e9-152bac87d58f # Environment variables
handle: craftEnvironment
instructions: 'dev / staging / production'
name: 'Craft Environment'
searchable: false
settings:
  validationRule: ''
  variableName: CRAFT_ENVIRONMENT
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
