columnSuffix: null
contentColumnType: string
fieldGroup: d50026f3-a236-4ae2-b00a-af55076acd17 # Site
handle: emailSender
instructions: null
name: 'Email Sender'
searchable: false
settings:
  validationRule: ''
  variableName: EMAIL_SENDER
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
