columnSuffix: null
contentColumnType: string
fieldGroup: 320fb86e-2364-403c-b8e9-152bac87d58f # Environment variables
handle: emailSender
instructions: null
name: 'Email Sender'
searchable: false
settings:
  validationRule: ''
  variableName: EMAIL_SENDER
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
