columnSuffix: null
contentColumnType: string
fieldGroup: 669ee208-7bb0-4800-ba43-454bc31751ac # Story
handle: storyTeam
instructions: null
name: 'Story Team'
searchable: false
settings:
  contentTable: '{{%matrixcontent_storyteam}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
