columnSuffix: null
contentColumnType: string
fieldGroup: 320fb86e-2364-403c-b8e9-152bac87d58f # Environment variables
handle: systemName
instructions: 'The System name as used in the Control Panel'
name: 'System Name'
searchable: false
settings:
  validationRule: ''
  variableName: SYSTEM_NAME
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
