columnSuffix: null
contentColumnType: string
fieldGroup: d50026f3-a236-4ae2-b00a-af55076acd17 # Site
handle: useViteDevServer
instructions: '0 / 1'
name: 'Use Vite Dev Server'
searchable: false
settings:
  validationRule: boolean
  variableName: VITE_USE_DEV_SERVER
translationKeyFormat: null
translationMethod: none
type: modules\main\fields\EnvironmentVariableField
