assets:
  tempVolumeUid: ed627edd-73bd-4b75-8684-f410bf4e4b9d # Temporary Images
dateModified: 1675766729
elementSources:
  craft\elements\Asset:
    -
      heading: Site
      type: heading
    -
      disabled: false
      key: 'volume:5a0be839-14a2-465e-a504-bb63dd0281e9' # Images
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      heading: Internal
      type: heading
    -
      disabled: false
      key: 'volume:ed627edd-73bd-4b75-8684-f410bf4e4b9d' # Temporary Images
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      disabled: false
      key: 'volume:3b60e4f9-36bb-4456-bee5-67160b5a3108' # User Photos
      tableAttributes:
        - 'field:cc3fbab0-826f-4aed-b2aa-eeaecc2964bf' # Alt Text
        - imageSize
        - dateModified
        - link
      type: native
    -
      heading: Work
      type: heading
    -
      condition:
        class: craft\elements\conditions\assets\AssetCondition
        conditionRules:
          -
            class: craft\fields\conditions\TextFieldConditionRule
            fieldUid: cc3fbab0-826f-4aed-b2aa-eeaecc2964bf # Alt Text
            operator: empty
            uid: 8182e7e7-1f2a-4b12-abf5-9c937e885f4d
            value: ''
        elementType: craft\elements\Asset
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:8326efe2-6f9f-4744-a23b-76512dd63e7c'
      label: 'Missing Alt Text'
      tableAttributes:
        - imageSize
        - dateCreated
        - uploader
      type: custom
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: true
      key: '*'
      tableAttributes:
        - section
        - link
      type: native
    -
      heading: Site
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:84b98802-2548-4aed-b67e-fc97f6ed9e30' # Page
      tableAttributes:
        - 'field:e2e51276-3783-49cb-9ed0-22ae364fd49a' # Menu Title
        - type
        - slug
        - postDate
        - link
      type: native
    -
      disabled: false
      key: 'section:2f93cb45-a9ce-4284-8848-9eb001fb8a1c' # News
      tableAttributes:
        - postDate
        - author
        - link
      type: native
    -
      disabled: false
      key: 'section:abd279ac-58c4-41dc-ac32-d2e388e34252' # Legal
      tableAttributes:
        - type
        - postDate
        - author
        - link
      type: native
    -
      heading: Embedded
      type: heading
    -
      disabled: false
      key: 'section:27127353-b8d1-4c07-a2af-7a273ad8f1f6' # Hero Area
      tableAttributes:
        - 'field:7df417e8-1eea-46d8-85a7-2a20370a881e' # Hero Image
        - postDate
      type: native
    -
      heading: Work
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        elementType: craft\elements\Entry
        fieldContext: global
      key: 'custom:fb2df323-df89-408a-8062-7efaa55f4469'
      label: Drafts
      tableAttributes:
        - section
        - type
        - drafts
      type: custom
email:
  fromEmail: $EMAIL_ADDRESS
  fromName: $EMAIL_SENDER
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: $SMTP_ENCRYPTION_METHOD
    host: $SMTP_HOST
    password: $SMTP_PASSWORD
    port: $SMTP_PORT
    timeout: '10'
    useAuthentication: $SMTP_AUTHENTICATION
    username: $SMTP_USER
  transportType: craft\mail\transportadapters\Smtp
fs:
  imagesTransforms_local:
    hasUrls: true
    name: 'Images Transforms Local'
    settings:
      path: '@webroot/assets/transforms'
    type: craft\fs\Local
    url: '@web/assets/transforms'
  images_local:
    hasUrls: false
    name: 'Images Local'
    settings:
      path: '@root/volumes/images'
    type: craft\fs\Local
    url: null
  tempimages_local:
    hasUrls: false
    name: 'Temp Images Local'
    settings:
      path: '@root/volumes/temp'
    type: craft\fs\Local
    url: '@web/files/temp'
  userPhotos_local:
    hasUrls: false
    name: 'User Photos Local'
    settings:
      path: '@root/volumes/userphotos'
    type: craft\fs\Local
    url: '@web/files/userphotos'
meta:
  __names__:
    0b3d2dae-0516-4e85-b297-c9e661b964d5: Heading # Heading
    0c39cdb5-26f9-49ca-9bb4-445a28a61ddf: Images # Images
    1b04edb4-5ebc-45da-ba85-afcd734f187b: 'YouTube Video' # YouTube Video
    1b464b23-6750-460e-aea1-0c4af5f52e23: Key # Key
    1b934de4-d292-4d6f-b40f-ba2b0120b6c8: 'System Name' # System Name
    1c948380-c11c-45f9-a668-2a5eac6f24c9: Settings # Settings
    1de27fd9-bda6-4977-8d43-b36ef6813c60: Level # Level
    1f5834fd-ed0d-466a-b4dd-2891fd144893: 'Show Structure Navigation' # Show Structure Navigation
    2a1eaa07-5692-4473-9f2d-02ca85f81dfd: 'Text Modules' # Text Modules
    2bfd1710-35e5-41cb-a655-1fdaf49a0d7c: 'Featured Entries' # Featured Entries
    02d2113e-298a-47c6-a40e-413a682ac7c5: Question # Question
    2f93cb45-a9ce-4284-8848-9eb001fb8a1c: News # News
    3b60e4f9-36bb-4456-bee5-67160b5a3108: 'User Photos' # User Photos
    3bb09a1c-cb36-438e-b8d5-0b35b0965f4e: Default # Default
    3cb8a841-f986-4959-8f1a-c44fe16ff8d1: Answer # Answer
    3d8293ac-fa84-47ed-befa-a41cb6315212: Layout # Layout
    3e35a043-a62e-4ede-acd6-44dfb92d6914: 'Site Name' # Site Name
    3fb81893-2727-4990-b8f6-a5f6e391a8d8: Style # Style
    4b050685-0425-4094-bde2-85e2eedd0e12: Text # Text
    4bc24da9-fd88-45ec-8410-bc189032e3f8: 'Phone Number' # Phone Number
    4bf7eb3c-ca42-4327-97e2-77533fc27a61: Caption # Caption
    5a0be839-14a2-465e-a504-bb63dd0281e9: Images # Images
    5b0c38db-9ab4-47d8-b4a7-913710c08ca6: English # English
    7b8b6f04-9d76-4b26-8276-96a80183750e: Quote # Quote
    7df417e8-1eea-46d8-85a7-2a20370a881e: 'Hero Image' # Hero Image
    7fda4ce3-4bdd-4fbe-b32f-35a5e6707295: 'News Index' # News Index
    8e7aba7b-4624-4470-b007-a84c85242f36: 'Sold Out' # Sold Out
    08f7545c-870e-4727-a418-660af19052ea: 'CTA Buttons' # CTA Buttons
    8f596240-23ec-46cd-abe2-386291b11179: 'Content Editors' # Content Editors
    9a3286bb-91f7-47ba-9862-9d102a8cf5d0: 'Show Hero Area' # Show Hero Area
    9c7e95a7-7a87-46ad-974e-8ce3846ef68b: Description # Description
    9d9d22d0-ccc2-4e4e-95b2-a28deb16c08b: Heading # Heading
    9e2e3c4b-bd17-46b3-97f0-a4f6605b93d9: Text # Text
    9efaa99a-273e-47a3-83f7-692251886873: Text # Text
    11f1c188-401c-44c4-bd0e-2b6d7b311fc6: Align # Align
    27b3f36f-ea97-4dad-a77d-39eff7bd0900: Key # Key
    48fde250-325a-44bf-9238-66f0e831a883: Image # Image
    61c8dfb5-4ac7-420b-ad8e-5cad0d464a98: Description # Description
    67a97a95-ddb9-4d73-a10b-649ba6d997cd: Privacy # Privacy
    72a3030d-cba4-4a39-ba7f-553d7116aeaf: Gallery # Gallery
    79c4d030-bf02-41c3-9a3e-260e28284dcf: 'Text Module' # Text Module
    080cb307-609c-4155-9c50-b6248db4d974: Text # Text
    81e6a0d6-13c5-47ad-a9e6-c2181276db9c: Text # Text
    84b98802-2548-4aed-b67e-fc97f6ed9e30: Page # Page
    94b76905-09aa-4aeb-82a0-222f592d42f8: 'Show in Sites' # Show in Sites
    99b1f33e-21a3-4870-8165-2b685034a641: Layout # Layout
    169ccd00-9c12-4921-b187-8ef8ca2ad525: Assets # Assets
    370cbaec-9bf1-4ecf-b903-276c6da6c861: 'Postal Address' # Postal Address
    400d2e7a-d260-459d-b16d-bc388f093106: Tagline # Tagline
    489e5502-a241-4b2e-97c5-d8a0220a72c6: 'CTA Target' # CTA Target
    605e973b-b2e9-4421-9f1a-80d4cddc0cf0: Parameter # Parameter
    621ad41b-f019-4e95-96aa-49f8c56482db: 'SEO Descriction' # SEO Descriction
    735b5e6e-8026-4de4-8e32-14e03d975565: Image # Image
    871e0a60-ea70-4650-91f2-746c9bc2de41: 'Aspect Ratio' # Aspect Ratio
    3468bd44-82e8-4104-932e-5085601fca12: Default # Default
    4120c3e9-17c2-464b-8d41-7d009dacb5e3: 'Page Template' # Page Template
    4401f3f7-9915-4cd0-b3d9-987755e4bdf8: Image # Image
    6193ce57-a570-451e-8124-ec3ba985b0b2: 'CTA Caption' # CTA Caption
    6739b2cb-a865-433d-9732-cdd6a419188d: 'Page Template' # Page Template
    8350d2ae-3d7d-4d96-aeae-eab90a7f0d5b: 'Hero Teaser' # Hero Teaser
    13852c19-7f9e-4e6b-8790-0063f0f21ab8: Default # Default
    44993cef-3718-479f-8c88-bdede1d256ba: 'Card Text' # Card Text
    52144f06-b394-45aa-bee6-d00e1f86878f: Primary # Primary
    75980a78-5a14-4d80-8e9c-b0616d62e02e: 'Hero Area' # Hero Area
    90724a6b-55ad-446f-be50-7aea7e1fb067: Robots # Robots
    97742dae-23f0-4986-a259-c886b727a452: FAQ # FAQ
    481205e6-eb29-45a0-8b40-021d4dcfcac1: 'Email Sender' # Email Sender
    655243f7-46a2-42c0-8de4-188017c31d53: 'Hero Area Template' # Hero Area Template
    5286148d-12b9-4f55-a35c-0e51c06bbe44: Contact # Contact
    8785637f-8785-4fd2-86d2-9232d9674420: 'Related Entries' # Related Entries
    27127353-b8d1-4c07-a2af-7a273ad8f1f6: 'Hero Area' # Hero Area
    34581043-4880-49b9-b16a-cba691fa21f3: Image # Image
    69164545-5879-454d-a57e-f703ca431331: Image # Image
    85898001-9c9c-4d46-abf9-a928e44f0d48: 'Body Content' # Body Content
    95358052-5e25-4a5d-bd52-58078b1a5aa2: FAQs # FAQs
    a08f1c5e-b057-468b-b989-6b243df4d213: Dynamic # Dynamic
    a1dd83a1-2011-4bef-aa20-b6d6a366d66e: 'SEO Image' # SEO Image
    a21f07ce-87f7-431d-b54c-a12786f9fc9c: 'Craft Environment' # Craft Environment
    a24e2c31-f1b3-4687-873d-b8d6dff03e10: Question # Question
    abd279ac-58c4-41dc-ac32-d2e388e34252: Legal # Legal
    abefa0bd-6b36-4b4f-a9de-a4304e7b66a3: 'Public Schema' # Public Schema
    ac457f93-1a50-473e-9983-a899a7f0bed7: Heading # Heading
    ad07bc26-df9d-4358-9fd9-f1ceb8e00af0: Sections # Sections
    addfffc1-5814-40f4-bb74-0e441740b9fa: FAQs # FAQs
    af9afec0-f712-4b14-b235-851c6455e267: Text # Text
    b0cfc7f4-d446-41bb-87ab-dc16b1481540: 'Alternative Title' # Alternative Title
    b3b9ebe4-94b8-4601-bf11-3c5aa638c87f: 'CTA Target' # CTA Target
    b7e84646-2ab1-476a-97a1-49ac1fa05852: 'Is Featured' # Is Featured
    b32ea3bc-ee43-4236-864d-972d36f184b2: Sitemap # Sitemap
    b61bea97-e4d4-4de2-9149-15f74906945a: SEO # SEO
    b64a3aa4-62b9-40c5-b05d-ea06389b36c7: 'Start Date' # Start Date
    b7361735-c91d-4877-a975-cfe6751133b1: Cards # Cards
    bb5f8fa8-90f9-4d54-9f99-3ccd6fb69a7b: Text # Text
    bbe2ff0f-6056-4848-80de-3070bb80294d: Email # Email
    bd76fb6e-8765-41d3-8e8a-02e37e127c80: Common # Common
    bf3d514d-a34d-41d6-bb20-61c6d8119820: 'Social Links' # Social Links
    c8a6470e-a8da-46c4-ae23-4eb68d320a66: 'Show in Sites' # Show in Sites
    c38ac7d1-9663-45a2-a78e-c676b354e27e: Search # Search
    c62d66b7-d193-453a-b154-4141fa6332c6: Quote # Quote
    c72e758a-f6c3-42cd-896b-3ff6353ed259: 'Featured Image' # Featured Image
    c908a30e-b8c5-44de-b9ee-7ae52d9c4c07: 'CTA Caption' # CTA Caption
    c38953ca-ba84-4992-8deb-65aa2fc40b34: 'Hero Area' # Hero Area
    c752550e-4c4a-4004-8229-7473dcf75450: 'Site Info' # Site Info
    cb919462-37df-4bb3-acf9-09892c4575e5: 'Nav Item' # Nav Item
    cc3fbab0-826f-4aed-b2aa-eeaecc2964bf: 'Alt Text' # Alt Text
    cce7e62c-f710-40fd-b9e9-71ba6f58265f: 'Hero Text' # Hero Text
    cf967bc8-e8fd-4cd3-b66c-998982d2cc6c: 'Booking Status' # Booking Status
    d1ce7a99-7ba0-4ad1-9f19-c4cdad3f247e: 'Email Address' # Email Address
    d92e63b4-996e-4dcd-8b55-d119540b5831: Default # Default
    d50026f3-a236-4ae2-b00a-af55076acd17: Site # Site
    db33cf09-8ba1-45f6-9cc0-3e855cbcb809: Template # Template
    dbf50cb2-37c8-45f7-b375-dcb93e09691b: Deutsch # Deutsch
    de3c08c7-8c44-46ea-8a7c-109499269f55: Answer # Answer
    dfe86fae-c542-4ae2-8b07-16d57c206b16: Button # Button
    e2e51276-3783-49cb-9ed0-22ae364fd49a: 'Menu Title' # Menu Title
    e41dea07-8368-4830-a643-ff8fa7f37200: Guides # Guides
    e53bc1f1-ecbf-44b8-a89f-bea86a68c048: Text # Text
    e62d63b0-c299-42ce-aeef-86a69f7e676c: 'SEO Fields' # SEO Fields
    eb6b24cc-83d7-416f-be4b-d002c7688b58: Copyright # Copyright
    eb61b6c1-d43a-4bf6-8091-bc71c44a9dcf: Entries # Entries
    ebe8548f-7f01-49b6-af98-56da49668e79: Logo # Logo
    ec70b604-43e4-45f8-bab5-0ab78983f3ce: 'Nav Item Template' # Nav Item Template
    ed627edd-73bd-4b75-8684-f410bf4e4b9d: 'Temporary Images' # Temporary Images
    ee6f8d07-ca81-4da0-991c-491e5108bff8: Home # Home
    f3c6560d-3487-4f65-a4f9-ac2926397b57: 'Aspect Ratio' # Aspect Ratio
    f8ff18c6-ca19-4910-8753-62aa768dd3a3: Cite # Cite
    f76ccc3a-7c88-43a3-9024-5ea619356bbf: Heading # Heading
    fbaae504-9220-4e1b-a58a-e3819e88194b: 'Use Vite Dev Server' # Use Vite Dev Server
    fbf00eb2-4a16-40ca-96bb-3fadd2bf459c: Default # Default
    fed0a20c-7c44-4de7-83d9-7843f8facfb8: 'Blitz Caching Enabled' # Blitz Caching Enabled
plugins:
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: ''
      allowedMessageFields: null
      prependSender: 'On behalf of'
      prependSubject: 'New message from Trail-quest'
      successFlashMessage: 'Thank you for your message! We received it and will reply as soon as possible.'
      toEmail: $EMAIL_ADDRESS
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      honeypotParam: contact
  contentoverview:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  elementmap:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: 7D1BJIWBEFGCQ4I0CE6C8WLE
    schemaVersion: 4.0.0
  inventory:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  seomate:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SYSTEM_NAME
  retryDuration: 30
  schemaVersion: 4.0.0.9
  timeZone: $SYSTEM_TIMEZONE
