fieldLayouts:
  f4019294-72d3-498d-a196-72612042deb5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3e35a043-a62e-4ede-acd6-44dfb92d6914 # Site Name
            instructions: 'As used in the front end'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f6b964a-7458-4e96-bbf6-7d922977be65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1b934de4-d292-4d6f-b40f-ba2b0120b6c8 # System Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9c3e3e7-43b6-4184-afa5-6b30cf30ad82
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 316efda6-6c53-4b7b-9cab-f18008350ee9
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eb6b24cc-83d7-416f-be4b-d002c7688b58 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: edb4663c-ed87-4c0d-80ee-fa175abb697c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ebe8548f-7f01-49b6-af98-56da49668e79 # Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 682f84eb-f62e-4211-a156-f8f302904d65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c72e758a-f6c3-42cd-896b-3ff6353ed259 # Featured Image
            instructions: null
            label: 'Default Featured Image'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a17c1872-4146-4578-9f61-54b0c65cbb05
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e034a3c-8cf7-46cb-a494-076274149e80
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 370cbaec-9bf1-4ecf-b903-276c6da6c861 # Postal Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1ee4cc86-fd3b-4c5a-a8b6-126e134bb46e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4bc24da9-fd88-45ec-8410-bc189032e3f8 # Phone Number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a9bdd21-bf46-45a2-b58f-9b52078cb4cf
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bbe2ff0f-6056-4848-80de-3070bb80294d # Email
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93e45923-92bc-4621-8c4e-e92635d3053d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bf3d514d-a34d-41d6-bb20-61c6d8119820 # Social Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 544fbedc-652c-48a6-870d-def3768fa4d2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Settings for sending system emails'
            type: craft\fieldlayoutelements\Heading
            uid: 74567a4c-4c35-4f10-a2d0-acd8f79efca4
            userCondition: null
          -
            elementCondition: null
            fieldUid: d1ce7a99-7ba0-4ad1-9f19-c4cdad3f247e # Email Address
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9ab522c0-8785-4c9d-8c88-d00f5f0df62b
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 719fb8f0-e1de-41bc-aee5-0cffac8a96d2
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 481205e6-eb29-45a0-8b40-021d4dcfcac1 # Email Sender
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5de2736a-9d8f-4c2a-9adf-07045925c4f4
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 5f361faf-6af3-4703-9eb8-5e1f5767a901
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 50
        name: 'Contact Info'
        uid: 5dc9b1dc-3459-46c0-a2de-b94398aab95c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Use __youtubeConsent__ as as key'
            type: craft\fieldlayoutelements\Tip
            uid: ca207e21-d768-4ba5-95c6-ffc57d49fb3c
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2a1eaa07-5692-4473-9f2d-02ca85f81dfd # Text Modules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e88c165a-f959-424f-9473-b9136b04549c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Contact Info'
            type: craft\fieldlayoutelements\Heading
            uid: 6edb1a73-f7e8-4bf7-8399-4da130e8d54c
            userCondition: null
        name: 'Text Modules'
        uid: 509a171b-c72c-438c-9736-fdeab41e4eac
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 621ad41b-f019-4e95-96aa-49f8c56482db # SEO Descriction
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f026524-a355-4411-a822-944ebbd41c45
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1dd83a1-2011-4bef-aa20-b6d6a366d66e # SEO Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb705374-5aed-4b8b-bcfe-ba9af7b1d0f5
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: de26a68f-7ada-4076-b3eb-0cf05f9f8bc4
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a21f07ce-87f7-431d-b54c-a12786f9fc9c # Craft Environment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e46b5663-6a06-45f1-bd77-09973a6d6b79
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 5139b8b2-445d-48ab-9c0b-255d8fe0cc39
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fed0a20c-7c44-4de7-83d9-7843f8facfb8 # Blitz Caching Enabled
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b26d798-9fc4-4a5e-91b3-5725526fabe2
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 8a0a6ff1-7e50-40bb-8604-93d13d71c92c
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: fbaae504-9220-4e1b-a58a-e3819e88194b # Use Vite Dev Server
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 981d2bd2-7d96-41db-bc28-f225b9984a1b
            userCondition:
              class: craft\elements\conditions\users\UserCondition
              conditionRules:
                -
                  class: craft\elements\conditions\users\AdminConditionRule
                  uid: 84a466ba-e070-41ca-a889-2ce9de68f125
                  value: true
              elementType: craft\elements\User
              fieldContext: global
            warning: null
            width: 25
        name: System
        uid: 409bfca0-9a0d-4d28-8a6d-565b2e765948
        userCondition:
          class: craft\elements\conditions\users\UserCondition
          conditionRules:
            -
              class: craft\elements\conditions\users\AdminConditionRule
              uid: 32f8cb32-b756-46b2-8cc1-257b4618b8ef
              value: true
          elementType: craft\elements\User
          fieldContext: global
handle: siteInfo
name: 'Site Info'
sortOrder: 1
